[project]
name = "cia"
version = "0.1.0"
description = "Classification of notarial acts"
readme = "README.md"
authors = [
    { name = "Natallia", email = "natakostina123@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic==1.19.1",
    "docling==2.121.0",
    "mlflow==3.15.2",
    "openai<3.0.0",
    "pgvector==0.5.0",
    "psycopg[binary]==3.3.4",
    "pydantic==2.13.4",
    "pydantic-settings==2.15.0",
    "pytest-cov==7.1.0",
    "sqlalchemy==2.0.52",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel==7.3.0",
    "jupyter==1.1.1",
    "loguru==0.7.3",
    "pytest==9.1.1",
    "pytest-mock==3.15.1",
    "rich==14.3.4",
    "ruff==0.16.6",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv]
add-bounds = "exact"
exclude-newer = "7 days"

[tool.ruff]
preview = true
line-length = 140
target-version = "py314"
exclude = [
    "alembic",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "E3"]

