"""Initial migration

Revision ID: 18e1714ce24c
Revises: 
Create Date: 2026-08-29 10:27:22.599975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '18e1714ce24c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('act_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Enum('AGR', 'APP', 'ATI', 'GAR', 'IMM', 'LAC', 'MAI', 'TER', 'VIG', name='act_label', native_enum=False), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('act_id')
    )
    op.create_index('ix_acts_act_id', 'acts', ['act_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_acts_act_id', table_name='acts')
    op.drop_table('acts')
    # ### end Alembic commands ###
