"""change_label_enum

Revision ID: 76ad19b1e8f0
Revises: 26d6884b2bde
Create Date: 2026-08-29 21:38:30.306087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '76ad19b1e8f0'
down_revision: Union[str, Sequence[str], None] = '26d6884b2bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acts', 'label',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Enum('AGR', 'APP', 'ATI', 'GAR', 'IMM', 'LAC', 'MAI', 'TER', 'VIG', 'TEST', name='act_label', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('acts', 'label',
               existing_type=sa.Enum('AGR', 'APP', 'ATI', 'GAR', 'IMM', 'LAC', 'MAI', 'TER', 'VIG', 'TEST', name='act_label', native_enum=False),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
